// Package bootstrap reverse-engineers a first-pass C4 model from a repo's real
// Go import graph, so the FIRST `nugit pr-render` on a brownfield repo is green
// (model matches code) instead of failing on every pre-existing edge.
//
// It reuses internal/goimports for discovery + edges, which is the SAME analysis
// the c4<->code check runs — so the generated model and the check agree by
// construction. Go-only for now (other languages deferred, PLAN.md I1).
package bootstrap

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/n8o/nugit/internal/cmake"
	"github.com/n8o/nugit/internal/gitutil"
	"github.com/n8o/nugit/internal/goimports"
	"github.com/n8o/nugit/internal/mapping"
	"github.com/n8o/nugit/internal/model"
)

// Component is a discovered package directory that becomes a C4 component.
type Component struct {
	ID   string // DSL identifier, unique
	Name string // human label (last path segment)
	Dir  string // nugit-root-relative package directory ("." for the root)
	Glob string // git-root-relative paths glob (carries the nested-module prefix)
}

// Graph is the discovered package graph.
type Graph struct {
	Module     string
	Components []Component // sorted by Dir
	Edges      [][2]string // [srcID, dstID], sorted, deduped, no self-edges
	// Structural is true when components came from the directory layout (no
	// language analysis), so relationships were NOT derived.
	Structural bool
}

// skipDir reports directories that never contain reviewable first-party packages.
func skipDir(name string) bool {
	switch name {
	case ".git", ".nugit", "vendor", "testdata", "node_modules", "third_party":
		return true
	}
	return strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")
}

// Discover walks repoDir and builds the package graph from build-included,
// non-test Go files (the same inclusion rule the c4<->code check uses).
func Discover(repoDir string) (Graph, error) {
	module, _ := goimports.ModulePath(repoDir)

	hasPkg := map[string]bool{}
	importsOf := map[string]map[string]bool{} // dir -> set of imported internal dirs

	err := filepath.WalkDir(repoDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if p != repoDir && skipDir(d.Name()) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}
		rel, _ := filepath.Rel(repoDir, p)
		rel = filepath.ToSlash(rel)
		b, e := os.ReadFile(p)
		if e != nil {
			return nil // unreadable file contributes nothing
		}
		dirs, included := goimports.Analyze(module, rel, string(b))
		if !included {
			return nil // _test.go or build-excluded: not architecture
		}
		dir := slashDir(rel)
		hasPkg[dir] = true
		if importsOf[dir] == nil {
			importsOf[dir] = map[string]bool{}
		}
		for _, id := range dirs {
			importsOf[dir][id] = true
		}
		return nil
	})
	if err != nil {
		return Graph{}, err
	}

	dirs := make([]string, 0, len(hasPkg))
	for d := range hasPkg {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	// prefix is the nugit root's location within the git repo (e.g.
	// "apps/operator/"), "" when they coincide or the dir isn't in a git repo.
	// Globs are emitted git-root-relative so they match git's diff paths.
	prefix := gitutil.Repo{Dir: repoDir}.Prefix()

	idOf := assignIDs(dirs)
	g := Graph{Module: module}
	mcomps := make([]model.Component, 0, len(dirs))
	for _, d := range dirs {
		id := idOf[d]
		glob := gitRootGlob(prefix, d)
		g.Components = append(g.Components, Component{ID: id, Name: lastSeg(d), Dir: d, Glob: glob})
		mcomps = append(mcomps, model.Component{ID: id, Paths: []string{glob}})
	}

	// Attribute edges with the SAME glob resolution the c4<->code check uses
	// (mapping.ResolveDir over the generated globs), so the generated model and
	// the check agree by construction — never an exact-dir-vs-glob mismatch.
	mp := mapping.New(model.Model{Components: mcomps})
	edgeSet := map[[2]string]bool{}
	for _, d := range dirs {
		src := idOf[d]
		for imp := range importsOf[d] {
			dst := mp.ResolveDir(prefix + imp) // imports are module-relative; globs git-root-relative
			if dst == "" || dst == src {
				continue
			}
			edgeSet[[2]string{src, dst}] = true
		}
	}
	for e := range edgeSet {
		g.Edges = append(g.Edges, e)
	}
	sort.Slice(g.Edges, func(i, j int) bool {
		if g.Edges[i][0] != g.Edges[j][0] {
			return g.Edges[i][0] < g.Edges[j][0]
		}
		return g.Edges[i][1] < g.Edges[j][1]
	})
	return g, nil
}

// GenerateDSL renders a Graph as a Structurizr-DSL workspace that round-trips
// through internal/c4 and leaves c4<->code green.
func GenerateDSL(g Graph, name string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "workspace %q %q {\n\n", name,
		"Auto-generated by `nugit init` — review and refine, then set c4.mode to enforce.")
	b.WriteString("  model {\n")
	if g.Structural {
		b.WriteString("    // Structural model: components from the directory layout.\n")
		b.WriteString("    // Relationships were NOT derived (no language analysis) — declare them\n")
		b.WriteString("    // by hand, or add a per-language analyzer to enforce them. c4<->code\n")
		b.WriteString("    // stays silent here, so a clean run is NOT an architecture guarantee.\n\n")
	}
	fmt.Fprintf(&b, "    sys = softwareSystem %q {\n\n", name)
	for _, c := range g.Components {
		fmt.Fprintf(&b, "      %s = component %q {\n        properties { paths %q }\n      }\n",
			c.ID, c.Name, c.Glob)
	}
	if len(g.Edges) > 0 {
		b.WriteString("\n")
		for _, e := range g.Edges {
			fmt.Fprintf(&b, "      %s -> %s\n", e[0], e[1])
		}
	}
	b.WriteString("    }\n  }\n\n")
	b.WriteString("  views {\n    component sys \"Components\" {\n      include *\n      autolayout lr\n    }\n    theme default\n  }\n}\n")
	return b.String()
}

// DetectCMake reports whether rootDir is a CMake project.
func DetectCMake(rootDir string) bool { return cmake.Detect(rootDir) }

// DiscoverCMake builds a component graph from CMake's target_link_libraries:
// directory-level components (dirs that define targets) WITH edges (link deps),
// statically, no configure. The root "." aggregate targets are dropped for a
// clean first-pass model. This makes a C++/CMake repo's architecture enforceable.
func DiscoverCMake(repoDir string) (Graph, error) {
	cg, err := cmake.Discover(repoDir)
	if err != nil {
		return Graph{}, err
	}
	prefix := gitutil.Repo{Dir: repoDir}.Prefix()

	var dirs []string
	for _, d := range cg.Dirs {
		if d != "." {
			dirs = append(dirs, d)
		}
	}
	idOf := assignIDs(dirs)
	g := Graph{}
	for _, d := range dirs {
		g.Components = append(g.Components, Component{ID: idOf[d], Name: lastSeg(d), Dir: d, Glob: gitRootGlob(prefix, d)})
	}
	edgeSet := map[[2]string]bool{}
	for _, e := range cg.Edges {
		s, sok := idOf[e[0]]
		t, tok := idOf[e[1]]
		if sok && tok && s != t {
			edgeSet[[2]string{s, t}] = true
		}
	}
	for e := range edgeSet {
		g.Edges = append(g.Edges, e)
	}
	sort.Slice(g.Edges, func(i, j int) bool {
		if g.Edges[i][0] != g.Edges[j][0] {
			return g.Edges[i][0] < g.Edges[j][0]
		}
		return g.Edges[i][1] < g.Edges[j][1]
	})
	return g, nil
}

// gitRootGlob returns the git-root-relative paths glob for a nugit-root-relative
// dir, carrying the nested-module prefix (e.g. "apps/operator/"). When prefix=""
// it is byte-identical to the old repo-root-relative behavior.
func gitRootGlob(prefix, dir string) string {
	if dir == "." || dir == "" {
		return prefix + "*.go" // root files of the nugit root only (never the whole tree)
	}
	return prefix + dir + "/**"
}

// assignIDs gives each dir a unique, parser-safe id: the last segment when
// unambiguous, else the sanitized full path, with a numeric suffix as a last
// resort. Deterministic given sorted input.
func assignIDs(dirs []string) map[string]string {
	out := map[string]string{}
	used := map[string]bool{}
	// The repo-root package gets a stable, readable id first (not "_").
	for _, d := range dirs {
		if d == "." {
			out["."] = "root"
			used["root"] = true
		}
	}
	count := map[string]int{}
	cand := map[string]string{}
	for _, d := range dirs {
		if d == "." {
			continue
		}
		c := sanitize(lastSeg(d))
		cand[d] = c
		count[c]++
	}
	for _, d := range dirs {
		if d == "." {
			continue
		}
		id := cand[d]
		if id == "" || count[id] > 1 || used[id] {
			id = sanitize(slashToUnderscore(d)) // disambiguate with the full path
		}
		base := id
		for n := 2; used[id]; n++ {
			id = fmt.Sprintf("%s_%d", base, n)
		}
		used[id] = true
		out[d] = id
	}
	return out
}

func lastSeg(dir string) string {
	if dir == "." || dir == "" {
		return "root"
	}
	if i := strings.LastIndexByte(dir, '/'); i >= 0 {
		return dir[i+1:]
	}
	return dir
}

func slashDir(rel string) string {
	if i := strings.LastIndexByte(rel, '/'); i >= 0 {
		return rel[:i]
	}
	return "."
}

func slashToUnderscore(s string) string {
	return strings.ReplaceAll(s, "/", "_")
}

// sanitize makes a string a safe DSL identifier: [A-Za-z0-9_], not leading digit.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "pkg"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "c_" + out
	}
	return out
}
