// Package bootstrap reverse-engineers a first-pass C4 model from a repo's real
// Go import graph, so the FIRST `nugit pr-render` on a brownfield repo is green
// (model matches code) instead of failing on every pre-existing edge.
//
// It reuses internal/goimports for discovery + edges, which is the SAME analysis
// the c4<->code check runs — so the generated model and the check agree by
// construction. Go-only for now (other languages deferred, PLAN.md I1).
package bootstrap

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/n8o/nugit/internal/goimports"
)

// Component is a discovered package directory that becomes a C4 component.
type Component struct {
	ID   string // DSL identifier, unique
	Name string // human label (last path segment)
	Dir  string // repo-relative package directory ("." for repo root)
}

// Graph is the discovered package graph.
type Graph struct {
	Module     string
	Components []Component // sorted by Dir
	Edges      [][2]string // [srcID, dstID], sorted, deduped, no self-edges
}

// skipDir reports directories that never contain reviewable first-party packages.
func skipDir(name string) bool {
	switch name {
	case ".git", ".nugit", "vendor", "testdata", "node_modules":
		return true
	}
	return strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")
}

// Discover walks repoDir and builds the package graph from build-included,
// non-test Go files (the same inclusion rule the c4<->code check uses).
func Discover(repoDir string) (Graph, error) {
	module, _ := goimports.ModulePath(repoDir)

	hasPkg := map[string]bool{}
	importsOf := map[string]map[string]bool{} // dir -> set of imported internal dirs

	err := filepath.WalkDir(repoDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if p != repoDir && skipDir(d.Name()) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}
		rel, _ := filepath.Rel(repoDir, p)
		rel = filepath.ToSlash(rel)
		b, e := os.ReadFile(p)
		if e != nil {
			return nil // unreadable file contributes nothing
		}
		dirs, included := goimports.Analyze(module, rel, string(b))
		if !included {
			return nil // _test.go or build-excluded: not architecture
		}
		dir := slashDir(rel)
		hasPkg[dir] = true
		if importsOf[dir] == nil {
			importsOf[dir] = map[string]bool{}
		}
		for _, id := range dirs {
			importsOf[dir][id] = true
		}
		return nil
	})
	if err != nil {
		return Graph{}, err
	}

	dirs := make([]string, 0, len(hasPkg))
	for d := range hasPkg {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	idOf := assignIDs(dirs)
	g := Graph{Module: module}
	for _, d := range dirs {
		g.Components = append(g.Components, Component{ID: idOf[d], Name: lastSeg(d), Dir: d})
	}

	edgeSet := map[[2]string]bool{}
	for _, d := range dirs {
		for imp := range importsOf[d] {
			if !hasPkg[imp] || imp == d {
				continue // imported dir isn't a discovered component, or self-import
			}
			edgeSet[[2]string{idOf[d], idOf[imp]}] = true
		}
	}
	for e := range edgeSet {
		g.Edges = append(g.Edges, e)
	}
	sort.Slice(g.Edges, func(i, j int) bool {
		if g.Edges[i][0] != g.Edges[j][0] {
			return g.Edges[i][0] < g.Edges[j][0]
		}
		return g.Edges[i][1] < g.Edges[j][1]
	})
	return g, nil
}

// GenerateDSL renders a Graph as a Structurizr-DSL workspace that round-trips
// through internal/c4 and leaves c4<->code green.
func GenerateDSL(g Graph, name string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "workspace %q %q {\n\n", name,
		"Auto-generated by `nugit init` from the Go import graph — review and refine, then set c4.mode to enforce.")
	b.WriteString("  model {\n")
	fmt.Fprintf(&b, "    sys = softwareSystem %q {\n\n", name)
	for _, c := range g.Components {
		fmt.Fprintf(&b, "      %s = component %q {\n        properties { paths %q }\n      }\n",
			c.ID, c.Name, globFor(c.Dir))
	}
	if len(g.Edges) > 0 {
		b.WriteString("\n")
		for _, e := range g.Edges {
			fmt.Fprintf(&b, "      %s -> %s\n", e[0], e[1])
		}
	}
	b.WriteString("    }\n  }\n\n")
	b.WriteString("  views {\n    component sys \"Components\" {\n      include *\n      autolayout lr\n    }\n    theme default\n  }\n}\n")
	return b.String()
}

// globFor returns the paths glob that binds a component to its directory.
func globFor(dir string) string {
	if dir == "." || dir == "" {
		return "*.go" // repo-root files only (never the whole tree)
	}
	return dir + "/**"
}

// assignIDs gives each dir a unique, parser-safe id: the last segment when
// unambiguous, else the sanitized full path, with a numeric suffix as a last
// resort. Deterministic given sorted input.
func assignIDs(dirs []string) map[string]string {
	count := map[string]int{}
	cand := map[string]string{}
	for _, d := range dirs {
		c := sanitize(lastSeg(d))
		cand[d] = c
		count[c]++
	}
	out := map[string]string{}
	used := map[string]bool{}
	for _, d := range dirs {
		id := cand[d]
		if id == "" || count[id] > 1 || used[id] {
			id = sanitize(slashToUnderscore(d))
		}
		base := id
		for n := 2; used[id]; n++ {
			id = fmt.Sprintf("%s_%d", base, n)
		}
		used[id] = true
		out[d] = id
	}
	return out
}

func lastSeg(dir string) string {
	if dir == "." || dir == "" {
		return "root"
	}
	if i := strings.LastIndexByte(dir, '/'); i >= 0 {
		return dir[i+1:]
	}
	return dir
}

func slashDir(rel string) string {
	if i := strings.LastIndexByte(rel, '/'); i >= 0 {
		return rel[:i]
	}
	return "."
}

func slashToUnderscore(s string) string {
	return strings.ReplaceAll(s, "/", "_")
}

// sanitize makes a string a safe DSL identifier: [A-Za-z0-9_], not leading digit.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "pkg"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "c_" + out
	}
	return out
}
