package c4

import (
	"fmt"
	"sort"
	"strings"

	"github.com/n8o/nugit/internal/model"
)

// GenArchLint renders the model as a go-arch-lint v3 config (.go-arch-lint.yml):
// each C4 component becomes a go-arch-lint component (bound by its path globs),
// and each declared relationship becomes an allowed dependency. This gives a Go
// team a second, independent enforcement of the same model in CI — deterministic
// and derived, never hand-maintained.
func GenArchLint(m model.Model) string {
	comps := append([]model.Component(nil), m.Components...)
	sort.Slice(comps, func(i, j int) bool { return comps[i].ID < comps[j].ID })

	// component id -> sorted allowed targets
	allow := map[string][]string{}
	for _, c := range comps {
		allow[c.ID] = nil
	}
	for _, r := range m.Relationships {
		if _, ok := allow[r.Src]; ok {
			allow[r.Src] = append(allow[r.Src], r.Dst)
		}
	}

	var b strings.Builder
	b.WriteString("# generated by `nugit c4 gen-rules` — do not edit by hand\n")
	b.WriteString("version: 3\n")
	b.WriteString("workdir: .\n")
	b.WriteString("allow:\n  depOnAnyVendor: true\n\n")

	b.WriteString("components:\n")
	for _, c := range comps {
		fmt.Fprintf(&b, "  %s:\n", c.ID)
		paths := append([]string(nil), c.Paths...)
		sort.Strings(paths)
		switch len(paths) {
		case 0:
			b.WriteString("    in: \"\"\n")
		case 1:
			fmt.Fprintf(&b, "    in: %s\n", paths[0])
		default:
			b.WriteString("    in:\n")
			for _, p := range paths {
				fmt.Fprintf(&b, "      - %s\n", p)
			}
		}
	}

	b.WriteString("\ndeps:\n")
	for _, c := range comps {
		fmt.Fprintf(&b, "  %s:\n", c.ID)
		targets := dedupSorted(allow[c.ID])
		if len(targets) == 0 {
			b.WriteString("    mayDependOn: []\n")
			continue
		}
		b.WriteString("    mayDependOn:\n")
		for _, t := range targets {
			fmt.Fprintf(&b, "      - %s\n", t)
		}
	}
	return b.String()
}

func dedupSorted(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
