package c4

import (
	"fmt"
	"sort"
	"strings"

	"github.com/n8o/nugit/internal/model"
)

// GenArchLint renders the model as a go-arch-lint v3 config (.go-arch-lint.yml):
// each C4 component becomes a go-arch-lint component (bound by its path globs),
// and each declared relationship becomes an allowed dependency. This gives a Go
// team a second, independent enforcement of the same model in CI — deterministic
// and derived, never hand-maintained.
//
// Two-level parity (ADR-0017): a container with its OWN paths is emitted as a
// go-arch-lint component (paths-less wrapper containers are not emitted at
// all), and a relationship endpoint naming a container rolls DOWN to its child
// components (plus the container itself when path-bound) — go-arch-lint has no
// container level, so the roll-up rule is expanded into the flat cross-product
// it permits.
func GenArchLint(m model.Model) string {
	// Merge components by id (a duplicate id would otherwise emit a duplicate YAML
	// key); union their path globs.
	byID := map[string]*model.Component{}
	var ids []string
	for i := range m.Components {
		c := m.Components[i]
		if ex, ok := byID[c.ID]; ok {
			ex.Paths = append(ex.Paths, c.Paths...)
		} else {
			cp := c
			byID[cp.ID] = &cp
			ids = append(ids, cp.ID)
		}
	}
	// Containers with own paths join the emitted set; children stay indexed for
	// endpoint expansion either way.
	children := map[string][]string{}
	for _, c := range m.Components {
		if c.Container != "" {
			children[c.Container] = append(children[c.Container], c.ID)
		}
	}
	ctPathBound := map[string]bool{}
	for i := range m.Containers {
		ct := m.Containers[i]
		if len(ct.Paths) == 0 {
			continue
		}
		ctPathBound[ct.ID] = true
		if ex, ok := byID[ct.ID]; ok {
			ex.Paths = append(ex.Paths, ct.Paths...)
		} else {
			byID[ct.ID] = &model.Component{ID: ct.ID, Paths: append([]string(nil), ct.Paths...)}
			ids = append(ids, ct.ID)
		}
	}
	sort.Strings(ids)

	// expand maps a relationship endpoint to the emitted components it stands
	// for: a component is itself; a container is its child components plus
	// itself when path-bound; anything else expands to nothing (edge dropped).
	expand := func(id string) []string {
		if _, ok := m.Container(id); ok {
			out := append([]string(nil), children[id]...)
			if ctPathBound[id] {
				out = append(out, id)
			}
			return out
		}
		if _, ok := byID[id]; ok {
			return []string{id}
		}
		return nil // never emit a mayDependOn touching a non-existent component
	}

	// id -> allowed targets (cross-product of both expanded endpoints).
	allow := map[string][]string{}
	for _, r := range m.Relationships {
		srcs, dsts := expand(r.Src), expand(r.Dst)
		if len(srcs) == 0 || len(dsts) == 0 {
			continue
		}
		for _, s := range srcs {
			allow[s] = append(allow[s], dsts...)
		}
	}

	var b strings.Builder
	b.WriteString("# generated by `nugit c4 gen-rules` — do not edit by hand\n")
	b.WriteString("version: 3\n")
	b.WriteString("workdir: .\n")
	b.WriteString("allow:\n  depOnAnyVendor: true\n\n")

	b.WriteString("components:\n")
	for _, id := range ids {
		paths := dedupSorted(byID[id].Paths)
		fmt.Fprintf(&b, "  %s:\n", yamlStr(id))
		switch len(paths) {
		case 0:
			b.WriteString("    in: \"\"\n")
		case 1:
			fmt.Fprintf(&b, "    in: %s\n", yamlStr(paths[0]))
		default:
			b.WriteString("    in:\n")
			for _, p := range paths {
				fmt.Fprintf(&b, "      - %s\n", yamlStr(p))
			}
		}
	}

	b.WriteString("\ndeps:\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "  %s:\n", yamlStr(id))
		targets := dedupSorted(allow[id])
		if len(targets) == 0 {
			b.WriteString("    mayDependOn: []\n")
			continue
		}
		b.WriteString("    mayDependOn:\n")
		for _, t := range targets {
			fmt.Fprintf(&b, "      - %s\n", yamlStr(t))
		}
	}
	return b.String()
}

// yamlStr emits a double-quoted YAML scalar so a value/key that looks like a bool,
// number, null, or contains ":" / YAML-special chars is never silently retyped or
// breaks the document.
func yamlStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func dedupSorted(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
