package c4

import (
	"fmt"
	"sort"
	"strings"

	"github.com/n8o/nugit/internal/model"
)

// GenArchLint renders the model as a go-arch-lint v3 config (.go-arch-lint.yml):
// each C4 component becomes a go-arch-lint component (bound by its path globs),
// and each declared relationship becomes an allowed dependency. This gives a Go
// team a second, independent enforcement of the same model in CI — deterministic
// and derived, never hand-maintained.
func GenArchLint(m model.Model) string {
	// Merge components by id (a duplicate id would otherwise emit a duplicate YAML
	// key); union their path globs.
	byID := map[string]*model.Component{}
	var ids []string
	for i := range m.Components {
		c := m.Components[i]
		if ex, ok := byID[c.ID]; ok {
			ex.Paths = append(ex.Paths, c.Paths...)
		} else {
			cp := c
			byID[cp.ID] = &cp
			ids = append(ids, cp.ID)
		}
	}
	sort.Strings(ids)

	// id -> allowed targets (only edges whose BOTH ends are real components).
	allow := map[string][]string{}
	for _, r := range m.Relationships {
		if _, okS := byID[r.Src]; !okS {
			continue
		}
		if _, okD := byID[r.Dst]; !okD {
			continue // never emit a mayDependOn to a non-existent component
		}
		allow[r.Src] = append(allow[r.Src], r.Dst)
	}

	var b strings.Builder
	b.WriteString("# generated by `nugit c4 gen-rules` — do not edit by hand\n")
	b.WriteString("version: 3\n")
	b.WriteString("workdir: .\n")
	b.WriteString("allow:\n  depOnAnyVendor: true\n\n")

	b.WriteString("components:\n")
	for _, id := range ids {
		paths := dedupSorted(byID[id].Paths)
		fmt.Fprintf(&b, "  %s:\n", yamlStr(id))
		switch len(paths) {
		case 0:
			b.WriteString("    in: \"\"\n")
		case 1:
			fmt.Fprintf(&b, "    in: %s\n", yamlStr(paths[0]))
		default:
			b.WriteString("    in:\n")
			for _, p := range paths {
				fmt.Fprintf(&b, "      - %s\n", yamlStr(p))
			}
		}
	}

	b.WriteString("\ndeps:\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "  %s:\n", yamlStr(id))
		targets := dedupSorted(allow[id])
		if len(targets) == 0 {
			b.WriteString("    mayDependOn: []\n")
			continue
		}
		b.WriteString("    mayDependOn:\n")
		for _, t := range targets {
			fmt.Fprintf(&b, "      - %s\n", yamlStr(t))
		}
	}
	return b.String()
}

// yamlStr emits a double-quoted YAML scalar so a value/key that looks like a bool,
// number, null, or contains ":" / YAML-special chars is never silently retyped or
// breaks the document.
func yamlStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func dedupSorted(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
