// Package render projects a computed Report into the three keystone outputs:
// a human markdown comment (with progressive disclosure), a GitHub check-run
// conclusion, and a structured-delta JSON for reviewer agents.
//
// The markdown narrative is templated from the deltas — deterministic, no LLM.
// An LLM prose layer is a later, optional enhancement (§9.5); the keystone
// deliberately ships without it so the view is reproducible.
package render

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/burrowfarm/nugit/internal/model"
)

// Markdown builds the sticky PR comment.
func Markdown(rep model.Report) string {
	var b strings.Builder
	tier := rep.Significance.Tier
	fmt.Fprintf(&b, "## nugit — PR view · %s\n\n", tierLabel(tier))
	b.WriteString(narrative(rep))
	b.WriteString("\n\n")
	if len(rep.Significance.Reasons) > 0 {
		fmt.Fprintf(&b, "_Significance: %s_\n\n", strings.Join(rep.Significance.Reasons, "; "))
	}

	// Consistency first — it is the trust core and always shown.
	b.WriteString(consistencySection(rep.Findings))
	b.WriteString("\n")

	expandArch := tier == model.TierArchitectural || !rep.C4.Empty()
	expandCode := true // code delta always relevant
	expandKnow := tier != model.TierTrivial && !rep.Knowledge.Empty()

	b.WriteString(details("🏛 Architecture delta (C4)", c4Section(rep.C4), expandArch))
	b.WriteString(details("📝 Code delta (grouped by component)", codeSection(rep.Code), expandCode))
	b.WriteString(details("📚 Knowledge delta", knowledgeSection(rep.Knowledge), expandKnow))
	if rep.Plan.Present {
		b.WriteString(details("📍 Plan position", planSection(rep.Plan), tier == model.TierArchitectural))
	}

	b.WriteString("\n---\n")
	b.WriteString("_Generated by `nugit pr-render` · deltas computed deterministically from this PR's own committed artifacts; no external datastore._\n")
	return b.String()
}

// narrative renders the deterministic "we were here → adding X → why" line.
func narrative(rep model.Report) string {
	var parts []string
	switch {
	case !rep.C4.Empty():
		parts = append(parts, fmt.Sprintf("This PR **changes the architecture** (%s)", c4Summary(rep.C4)))
	case rep.Significance.Tier == model.TierArchitectural:
		parts = append(parts, "This PR is **architecturally significant** (a cross-component dependency changed)")
	case rep.Significance.Tier == model.TierTrivial:
		parts = append(parts, "This is a **trivial** change")
	default:
		parts = append(parts, "This PR changes code")
	}
	if n := len(rep.Code.Files); n > 0 {
		parts = append(parts, fmt.Sprintf("%d file(s) (+%d/-%d) across %d component(s)",
			n, rep.Code.TotalAdd, rep.Code.TotalDel, componentCount(rep.Code)))
	}
	if !rep.Knowledge.Empty() {
		parts = append(parts, fmt.Sprintf("%d knowledge object(s)", len(rep.Knowledge.Changes)))
	}
	if fails := countSev(rep.Findings, model.SevFail); fails > 0 {
		parts = append(parts, fmt.Sprintf("⚠️ **%d consistency failure(s)** block clean review", fails))
	}
	return strings.Join(parts, "; ") + "."
}

func consistencySection(fs []model.Finding) string {
	var b strings.Builder
	fails := countSev(fs, model.SevFail)
	warns := countSev(fs, model.SevWarn)
	header := "### Cross-artifact consistency"
	switch {
	case fails > 0:
		fmt.Fprintf(&b, "%s — ❌ %d failure(s), %d warning(s)\n\n", header, fails, warns)
	case warns > 0:
		fmt.Fprintf(&b, "%s — ⚠️ %d warning(s)\n\n", header, warns)
	default:
		fmt.Fprintf(&b, "%s — ✅ no inconsistencies detected\n\n", header)
		return b.String()
	}
	for _, f := range fs {
		fmt.Fprintf(&b, "- %s **%s** `%s` — %s\n  %s\n", sevIcon(f.Severity), f.Severity, f.Check, esc(f.Title), esc(f.Detail))
	}
	return b.String()
}

func c4Section(d model.C4Delta) string {
	if d.Empty() {
		return "_No change to `workspace.dsl`._\n"
	}
	var b strings.Builder
	for _, c := range d.AddedComponents {
		fmt.Fprintf(&b, "- ➕ component **%s** (%s)\n", c.ID, nameOr(c))
	}
	for _, c := range d.RemovedComponents {
		fmt.Fprintf(&b, "- ➖ component **%s** (%s)\n", c.ID, nameOr(c))
	}
	for _, c := range d.ChangedComponents {
		fmt.Fprintf(&b, "- ✏️ component **%s** changed: %s\n", c.After.ID, strings.Join(c.Fields, ", "))
	}
	for _, r := range d.AddedRels {
		fmt.Fprintf(&b, "- ➕ relationship `%s → %s`%s\n", r.Src, r.Dst, descSuffix(r.Desc))
	}
	for _, r := range d.RemovedRels {
		fmt.Fprintf(&b, "- ➖ relationship `%s → %s`%s\n", r.Src, r.Dst, descSuffix(r.Desc))
	}
	for _, rc := range d.ChangedRels {
		fmt.Fprintf(&b, "- ✏️ relationship `%s → %s` description: %q → %q\n",
			rc.After.Src, rc.After.Dst, rc.Before.Desc, rc.After.Desc)
	}
	return b.String()
}

func codeSection(d model.CodeDelta) string {
	if len(d.Files) == 0 {
		return "_No code files changed._\n"
	}
	var b strings.Builder
	comps := make([]string, 0, len(d.ByComp))
	for c := range d.ByComp {
		comps = append(comps, c)
	}
	sort.Strings(comps)
	for _, c := range comps {
		label := c
		if c == "" {
			label = "(unmapped — no C4 component owns these paths)"
		}
		fmt.Fprintf(&b, "\n**%s**\n", label)
		for _, f := range d.ByComp[c] {
			fmt.Fprintf(&b, "- `%s` %s (+%d/-%d)\n", f.Path, statusWord(f.Status), f.Added, f.Deleted)
		}
	}
	return b.String()
}

func knowledgeSection(d model.KnowledgeDelta) string {
	if d.Empty() {
		return "_No knowledge objects changed._\n"
	}
	var b strings.Builder
	for _, kc := range d.Changes {
		if kc.Object == nil {
			fmt.Fprintf(&b, "- %s `%s`\n", statusWord(kc.Status), kc.Path)
			continue
		}
		o := kc.Object
		fmt.Fprintf(&b, "- %s **%s** `%s` (%s, %s)\n", statusWord(kc.Status), o.Type, idOr(o), o.Scope, effectiveStatus(o))
		if o.Rejected != "" {
			fmt.Fprintf(&b, "  - 🚫 rejected: %s\n", esc(oneLine(o.Rejected)))
		}
	}
	return b.String()
}

func planSection(p model.PlanPosition) string {
	var b strings.Builder
	if len(p.Completed) > 0 {
		fmt.Fprintf(&b, "- ✅ done: %s\n", strings.Join(p.Completed, ", "))
	}
	if p.Current != "" {
		fmt.Fprintf(&b, "- ▶️ current: %s\n", p.Current)
	}
	if len(p.Remaining) > 0 {
		fmt.Fprintf(&b, "- ⏳ remaining: %s\n", strings.Join(p.Remaining, ", "))
	}
	if p.Note != "" {
		fmt.Fprintf(&b, "- _%s_\n", p.Note)
	}
	return b.String()
}

// ---- check-run ----

// CheckRun is the GitHub Checks API output subset nugit emits.
type CheckRun struct {
	Name       string `json:"name"`
	Conclusion string `json:"conclusion"` // success | neutral | failure
	Title      string `json:"title"`
	Summary    string `json:"summary"`
}

// Conclusion maps findings onto a check-run conclusion.
func Conclusion(rep model.Report) string {
	if countSev(rep.Findings, model.SevFail) > 0 {
		return "failure"
	}
	if countSev(rep.Findings, model.SevWarn) > 0 {
		return "neutral"
	}
	return "success"
}

// CheckRunJSON renders the check-run output as JSON.
func CheckRunJSON(rep model.Report) ([]byte, error) {
	cr := CheckRun{
		Name:       "nugit",
		Conclusion: Conclusion(rep),
		Title:      narrative(rep),
		Summary:    Markdown(rep),
	}
	return json.MarshalIndent(cr, "", "  ")
}

// StructuredJSON renders the full report for consumption by reviewer agents.
func StructuredJSON(rep model.Report) ([]byte, error) {
	return json.MarshalIndent(rep, "", "  ")
}

// ---- helpers ----

func details(summary, body string, open bool) string {
	o := ""
	if open {
		o = " open"
	}
	return fmt.Sprintf("<details%s><summary>%s</summary>\n\n%s\n</details>\n\n", o, summary, body)
}

func tierLabel(t model.Tier) string {
	switch t {
	case model.TierArchitectural:
		return "architectural 🏛"
	case model.TierFeature:
		return "feature ✨"
	default:
		return "trivial"
	}
}

func sevIcon(s model.Severity) string {
	switch s {
	case model.SevFail:
		return "❌"
	case model.SevWarn:
		return "⚠️"
	default:
		return "ℹ️"
	}
}

func countSev(fs []model.Finding, s model.Severity) int {
	n := 0
	for _, f := range fs {
		if f.Severity == s {
			n++
		}
	}
	return n
}

func componentCount(d model.CodeDelta) int {
	set := map[string]bool{}
	for _, f := range d.Files {
		set[f.Component] = true
	}
	return len(set)
}

func c4Summary(d model.C4Delta) string {
	var ps []string
	if n := len(d.AddedComponents); n > 0 {
		ps = append(ps, fmt.Sprintf("+%d component(s)", n))
	}
	if n := len(d.RemovedComponents); n > 0 {
		ps = append(ps, fmt.Sprintf("-%d component(s)", n))
	}
	if n := len(d.AddedRels) + len(d.RemovedRels); n > 0 {
		ps = append(ps, fmt.Sprintf("%d relationship change(s)", n))
	}
	if len(ps) == 0 {
		return "component metadata changed"
	}
	return strings.Join(ps, ", ")
}

func nameOr(c model.Component) string {
	if c.Name != "" {
		return c.Name
	}
	return c.ID
}

func descSuffix(d string) string {
	if d == "" {
		return ""
	}
	return " — " + d
}

func statusWord(s string) string {
	switch s {
	case "A":
		return "added"
	case "M":
		return "modified"
	case "D":
		return "removed"
	case "R":
		return "renamed"
	default:
		return s
	}
}

func effectiveStatus(o *model.KnowledgeObject) string {
	if o.EffectiveStatus != "" {
		return string(o.EffectiveStatus)
	}
	if o.Status != "" {
		return string(o.Status)
	}
	return "unknown"
}

func idOr(o *model.KnowledgeObject) string {
	if o.ID != "" {
		return o.ID
	}
	return o.Path
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > 200 {
		return s[:200] + "…"
	}
	return s
}

// esc neutralizes HTML-significant tokens in author-controlled text so a
// knowledge body or finding detail cannot break the <details> layout.
func esc(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
