package scaffold

import "fmt"

func configYML(mode string) string {
	return fmt.Sprintf(`# nugit configuration (keystone subset). Generated by `+"`nugit init`"+`.

schema_version: 1

c4:
  dsl: .nugit/architecture/workspace.dsl
  # mode: warn | enforce
  #   warn    — c4<->code reports undeclared dependencies as warnings (adoption)
  #   enforce — undeclared dependencies fail the check-run (ratified)
  # Start in warn while you refine the auto-generated model, then flip to enforce.
  mode: %s

significance:
  trivial_max_files: 2
  trivial_max_churn: 20

pr_render:
  fail_on: fail

capture:
  # commit_msg: warn | block | off — validate the trailer block on commit
  commit_msg: warn

narrative:
  # opt-in LLM prose summary (architectural PRs only; needs ANTHROPIC_API_KEY).
  # off by default — output is byte-identical to the deterministic view when off.
  enabled: false
`, mode)
}

func glossaryMD() string {
	return `---
schema_version: 1
id: GLOSSARY
type: glossary
scope: global
status: active
created: 2026-01-01T00:00:00Z
provenance:
  commit: nugit-init
confidence: medium
---

# Glossary

Define your project's domain vocabulary here, one term per bullet:

- **term** — definition.
`
}

// templateDSL is written when there is no Go import graph to bootstrap from
// (a non-Go repo, or --no-model). The user fills in components + paths globs.
func templateDSL(name string) string {
	return fmt.Sprintf(`workspace %q "Architecture model — define your components and bind each to its files." {

  model {
    sys = softwareSystem %q {

      # One component per logical unit. Bind it to physical files with a paths
      # glob — this is what lets nugit group the code delta and check that code
      # dependencies match the model.
      #
      # example = component "Example" {
      #   properties { paths "src/example/**" }
      # }
      #
      # Declare real dependencies between components:
      #   example -> other "uses"
    }
  }

  views {
    component sys "Components" {
      include *
      autolayout lr
    }
    theme default
  }
}
`, name, name)
}
